name: Pull Request Events

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5
        with:
          show-progress: false

      - name: 🕺️ Checkout model
        uses: actions/checkout@v5
        with:
          show-progress: false
        with:
          repository: ultralytics/yolov5
          path: yolov5

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.9

      - name: 📥 Download dependencies
        run: pip install -r requirements.tests.txt

      - name: 📥 Download model dependencies
        run: pip install -r requirements.txt
        working-directory: yolov5

      - name: 🏋️‍♀️ Download weights
        run: gdown ${{ secrets.WEIGHTS_ID }}
        working-directory: tower_scout

      - name: 🧪 Run tests
        run: pytest

      - name: 📤 Report coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov.xml
